### ISSUE TITLE
6DoF Mixer calculation example

### ISSUE THREAD

**Issue by mirkix** [IamPete1/Lynchpin#7]
Hello and thanks for the great work!

Could you please provide an example how you calculate the 6DoF Mixer for your frame. I have a slightly different frame and want to use a 6DoF LUA initialized mixer for that.

**Comment by IamPete1** [comment]
The format of the `Motors_6DoF:add_motor` call is:

`motor_num (0 indexed), roll_factor, pitch_factor, yaw_factor, throttle_factor, forward_factor, right_factor, reversible (bool), testing_order (1 indexed)`

You will have to wait until  my ArduPilot dev conference talk to find out how I got the factors for the Lynchpin.
